Vagrant.configure("2") do |config|
  config.vm.define "default", primary: true do |config_vm|
    config_vm.vm.box = "StefanScherer/windows_2019"
  end

  config.vm.define "2016", autostart: false do |config_vm|
    config_vm.vm.box = "StefanScherer/windows_2016"
  end

  config.vm.provider "virtualbox" do |v|
    v.linked_clone = true
    v.memory = 4096
    v.cpus = 2
  end

  config.vm.network :forwarded_port, guest: 3389, host: 53389, id: "rdp"
  config.vm.boot_timeout = 60
  config.vm.communicator = "winrm"
  config.winrm.port = 55985

end
